# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e42c74391b18caad9476c14dcc6c1643"
application_url = "https://postposted-aspect-faqs-byte.trycloudflare.com"
embedded = true
name = "teifi-remix-ts-beso"
handle = "teifi-remix-ts-beso"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://postposted-aspect-faqs-byte.trycloudflare.com/auth/callback",
  "https://postposted-aspect-faqs-byte.trycloudflare.com/auth/shopify/callback",
  "https://postposted-aspect-faqs-byte.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "beso-demo-store.myshopify.com"
automatically_update_urls_on_dev = true
